MODULES = compression_test

EXTENSION = compression_test
DATA = compression_test--1.0.sql
PGFILEDESC = "compression_test - utilities for various compression algorithms"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
