MODULES = mcxtalloc_test

EXTENSION = mcxtalloc_test
PGFILEDESC = "mcxtalloc_test - Test low-level allocation functions"
REGRESS = mcxtalloc_test

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
