MODULES = hmac_funcs

EXTENSION = hmac_funcs
REGRESS = hmac_funcs
DATA = hmac_funcs--1.0.sql
PGFILEDESC = "hmac_funcs - HMAC functions"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
