MODULES = pg_sasl_prepare

EXTENSION = pg_sasl_prepare
DATA = pg_sasl_prepare--1.0.sql
PGFILEDESC = "pg_sasl_prepare - SASLprepare for UTF-8 strings"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
