MODULES = pg_statvfs

EXTENSION = pg_statvfs
DATA = pg_statvfs--1.0.sql
PGFILEDESC = "pg_statvfs - Minimal extension template"

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
